name = "surface"
version = "0.1.0"
license = "LGPL-3.0-or-later"

[dependencies]
mctc-lib.git = "https://github.com/grimme-lab/mctc-lib"

[dev-dependencies]
mstore.git = "https://github.com/grimme-lab/mstore"
